/**
 * Calls the OpenAI GPT-4 API with the provided prompt text and returns the generated response.
 *
 * @example
 * const response = await callGPT4("Translate this text to Spanish.", "your-api-key-here");
 * console.log(response);
 *
 * @param promptText - The text prompt to send to GPT-4 for processing.
 * @param openAiApiKey - The OpenAI API key required for authentication.
 * @returns {Promise<string>} A promise that resolves to the response content generated by GPT-4.
 * @throws {Error} If the API request fails or returns an error.
 */
export async function callGPT4(
  promptText: string,
  openAiApiKey: string
): Promise<string> {
  const response = await fetch("https://api.openai.com/v1/chat/completions", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${openAiApiKey}`,
    },
    body: JSON.stringify({
      model: "gpt-4o",
      messages: [{ role: "user", content: promptText }],
    }),
  });

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(`Error calling the API: ${errorText}`);
  }

  const data = await response.json();
  return data.choices[0].message.content;
}
